#!/bin/bash

svnrev=`svn info http://gwtuml.googlecode.com/svn/trunk/ | sed -n '5 s/.*: //g p'`
if [ $svnrev = "" ]; then 
        svnrev="???"
else
	let svnrev=svnrev+1
fi

echo "Compiling for revision : "$svnrev
cd war
./makeHtml $svnrev
./makeRevLogo "r."$svnrev
rm -fr umldrawer
svn up umldrawer
svn rm --force umldrawer/*.cache.*
svn rm --force umldrawer/*.rpc
rm -f umldrawer/*.cache.*
rm -f umldrawer/*.rpc
mv umldrawer umldrawer_
cd ..
ant $1
cd war
cp -fr umldrawer/* umldrawer_
rm -fr umldrawer
mv umldrawer_ umldrawer
cd umldrawer
svn add --force *
notify-send "Build done !"
