#!/bin/bash

svnrev=`svn info http://gwtuml.googlecode.com/svn/trunk/ | sed -n '5 s/.*: //g p'`
if [ $svnrev = "" ]; then 
        svnrev="???"
else
	let svnrev=svnrev+1
fi

echo "Compiling for revision : "$svnrev
cd war
./makeHtml $svnrev
./makeRevLogo "r."$svnrev
rm -fr gwtumldrawer
svn up gwtumldrawer
svn rm --force gwtumldrawer/*.cache.*
svn rm --force gwtumldrawer/*.rpc
rm -f gwtumldrawer/*.cache.*
rm -f gwtumldrawer/*.rpc
mv gwtumldrawer gwtumldrawer_
cd ..
ant $1
cd war
cp -fr gwtumldrawer/* gwtumldrawer_
rm -fr gwtumldrawer
mv gwtumldrawer_ gwtumldrawer
cd gwtumldrawer
svn add --force *
notify-send "Build done !"
